version: "3.9"
services:
  backend:
    build: ./backend
    container_name: notes-backend
    ports:
      - "5000:5000"
  frontend:
    build: ./signapp
    container_name: notes-signapp
    ports:
      - "3000:3000"
    depends_on:
      - backend
